name: env01
channels:
  - defaults
dependencies:
  - anyio=3.5.0
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - asttokens=2.0.5
  - attrs=21.4.0
  - babel=2.9.1
  - backcall=0.2.0
  - beautifulsoup4=4.11.1
  - bleach=4.1.0
  - brotlipy=0.7.0
  - ca-certificates=2022.3.29
  - certifi=2021.10.8
  - cffi=1.15.0
  - charset-normalizer=2.0.4
  - cryptography=36.0.0
  - debugpy=1.5.1
  - decorator=5.1.1
  - defusedxml=0.7.1
  - entrypoints=0.4
  - executing=0.8.3
  - idna=3.3
  - importlib_resources=5.2.0
  - ipykernel=6.9.1
  - ipython=8.2.0
  - ipython_genutils=0.2.0
  - jedi=0.18.1
  - jinja2=3.0.3
  - json5=0.9.6
  - jsonschema=4.4.0
  - jupyter_client=7.2.2
  - jupyter_core=4.9.2
  - jupyter_server=1.13.5
  - jupyterlab=3.3.2
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.12.0
  - libffi=3.3
  - libsodium=1.0.18
  - markupsafe=2.0.1
  - matplotlib-inline=0.1.2
  - mistune=0.8.4
  - nbclassic=0.3.5
  - nbclient=0.5.13
  - nbconvert=6.4.4
  - nbformat=5.3.0
  - ncurses=6.3
  - nest-asyncio=1.5.5
  - notebook=6.4.8
  - openssl=1.1.1n
  - packaging=21.3
  - pandocfilters=1.5.0
  - parso=0.8.3
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=21.2.4
  - prometheus_client=0.13.1
  - prompt-toolkit=3.0.20
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycparser=2.21
  - pygments=2.11.2
  - pyopenssl=22.0.0
  - pyrsistent=0.18.0
  - pysocks=1.7.1
  - python=3.8.12
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.15.1
  - pyzmq=22.3.0
  - readline=8.1
  - requests=2.27.1
  - send2trash=1.8.0
  - setuptools=58.0.4
  - six=1.16.0
  - sniffio=1.2.0
  - soupsieve=2.3.1
  - sqlite=3.37.0
  - stack_data=0.2.0
  - terminado=0.13.1
  - testpath=0.5.0
  - tk=8.6.11
  - tornado=6.1
  - traitlets=5.1.1
  - typing-extensions=4.1.1
  - typing_extensions=4.1.1
  - urllib3=1.26.9
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=0.58.0
  - wheel=0.37.0
  - xz=5.2.5
  - zeromq=4.3.4
  - zipp=3.7.0
  - zlib=1.2.11
  - pip:
    - cvxpy==1.2.0
    - cycler==0.11.0
    - ecos==2.0.10
    - fonttools==4.28.5
    - iniconfig==1.1.1
    - joblib==1.1.0
    - kiwisolver==1.3.2
    - matplotlib==3.5.1
    - mosek==9.3.20
    - numpy==1.22.0
    - osqp==0.6.2.post5
    - pandas==1.3.5
    - pillow==9.0.0
    - pluggy==1.0.0
    - py==1.11.0
    - pybind11==2.9.0
    - pyparsing==3.0.6
    - pytest==6.2.5
    - pytz==2021.3
    - qdldl==0.1.5.post0
    - scikit-learn==1.0.2
    - scipy==1.7.3
    - scs==3.2.0
    - threadpoolctl==3.0.0
    - toml==0.10.2

